version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Map external port 8081 to internal port 8080
    networks:
      - techbot_network

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    ports:
      - "8082:50051" # Map external port 8082 to internal port 50051
    networks:
      - techbot_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000" # Map external port 8080 to internal port 3000
    networks:
      - techbot_network

networks:
  techbot_network:
    driver: bridge