# docker-test.yml
name: Docker Compose Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (Optional but good practice)
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file for services
        run: |
          echo "SOME_ENV_VAR=test_value" > .env
          echo "API_GATEWAY_URL=http://localhost:8081" >> .env
          echo "AI_SERVICE_GRPC_URL=localhost:8082" >> .env

      - name: Build and run services with Docker Compose
        run: docker-compose up -d --build

      - name: Check Docker Compose services status
        run: docker-compose ps
        
      - name: Show all Docker Compose logs (for debugging if tests fail)
        if: always()
        run: docker-compose logs --no-color
