# filepath: .github/workflows/docker-test.yml
name: Dockerfile Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t techbot_image .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 techbot_image

      - name: Check container logs
        run: docker logs $(docker ps -q)

      - name: Test if port 3000 is open
        run: netstat -tuln

      - name: Test services
        run: curl http://localhost:3000