# docker-test.yml
name: Docker Compose Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (Optional but good practice)
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file for services
        run: |
          echo "SOME_ENV_VAR=test_value" > .env
          echo "API_GATEWAY_URL=http://localhost:8081" >> .env
          echo "AI_SERVICE_GRPC_URL=localhost:8082" >> .env

      - name: Build and run services with Docker Compose
        run: docker-compose up -d --build

      - name: Check Docker Compose services status
        run: docker-compose ps

      - name: Wait for frontend service (port 8080)
        run: |
          echo "Waiting for frontend service on http://localhost:8080..."
          timeout 120 bash -c '
            while ! curl -s http://localhost:8080 > /dev/null; do
              echo "Frontend not ready yet. Retrying in 5 seconds..."
              sleep 5
            done
          '
          if [ $? -eq 124 ]; then
            echo "Frontend service did not become ready within 120 seconds."
            docker-compose logs frontend
            exit 1
          fi
          echo "Frontend service is ready!"

      - name: Run HTTP Tests (curl)
        run: |
          echo "--- Running HTTP Tests ---"
          echo "Testing Frontend (http://localhost:8080)..."
          curl -v http://localhost:8080
          echo "---------------------------"

      - name: Show all Docker Compose logs (for debugging if tests fail)
        if: always()
        run: docker-compose logs --no-color
