# filepath: .github/workflows/docker-test.yml
name: Dockerfile Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t techbot_image .

      - name: Run Docker container
        id: run_container
        run: echo $(docker run -d -p 3000:3000 techbot_image) > container_id.txt

      - name: Check container logs
        run: docker logs $(cat container_id.txt)

      - name: Test if port 3000 is open
        run: netstat -tuln

      - name: Test services
        run: curl http://localhost:3000